name: cheryclose_app
description: WhatsApp-first sales enablement app for Chery salespeople.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.10
  share_plus: ^7.2.1
  intl: ^0.18.1
  qr_flutter: ^4.1.0
  path_provider: ^2.1.2
  uuid: ^4.3.1
  file_saver: ^0.2.8
  screenshot: ^2.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/captions/
    - assets/models/
    - assets/posters/
